# Кофигурация с поддоменом и SSL сертификатами в файле nginx_subdomain.conf
user  root;
worker_processes  1;

events {
}

http {
    server {
        listen       6000;
        server_name  35.207.203.72;
        # server_name  mohir.cloud;
        # server_name  fleekapi.uz;

        location /api/ {
            proxy_pass http://backend:5000/;
        }
    }
}