worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen       6000;
        server_name  35.207.203.72;
        # server_name  mohir.cloud;
        # server_name  fleekapi.uz;

        location /api/ {
            proxy_pass http://backend:5000/;
        }
    }
}