worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name 35.207.203.72;

        location /api/ {
            proxy_pass http://backend:5000/;
        }
    }
}